CFLAGS=-std=c++11 -g
#FILES= main.cpp Lab01_Lex/lexer.h Lab01_Lex/lexer.cpp Lab01_Lex/token.h Lab01_Lex/token.cpp Lab02_Par/parser.h Lab02_Par/parser.cpp 
#parser: main.cpp Lab01_Lex/lexer.h Lab01_Lex/lexer.cpp Lab01_Lex/token.h Lab01_Lex/token.cpp Lab02_Par/parser.h Lab02_Par/parser.cpp 
FILES= *.h *.cpp
parser: *.h *.cpp
	g++ $(CFLAGS) $(FILES) -o parser
	
	
