CFLAGS=-std=c++11 -g
##FILES= main.cpp Lab01_Lex/lexer.h Lab01_Lex/lexer.cpp Lab01_Lex/token.h Lab01_Lex/token.cpp Lab02_Par/parser.h Lab02_Par/parser.cpp 
##parser: main.cpp Lab01_Lex/lexer.h Lab01_Lex/lexer.cpp Lab01_Lex/token.h Lab01_Lex/token.cpp Lab02_Par/parser.h Lab02_Par/parser.cpp 
FILES= *.h *.cpp
parser: *.h *.cpp
#	g++ $(CFLAGS) $(FILES) -o parser
	
#	g++ -Wall -Werror -std=c++11 -g *.cpp -o parser # command to run in command line
	
#	g++ -g -Wall -Werror -std=c++11 *.cpp -o parser

	g++ -Wall -Werror $(CFLAGS) -g $(FILES) -o parser